version: '3'

services:
  namenode:
    image: dslab/hadoop-namenode
    networks:
      - hdrs
    volumes:
      - namenode:/hadoop/dfs/name
    environment:
      - CLUSTER_NAME=test
    env_file:
      - ./hadoop.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    ports:
      - 9870:9870
      - 9000:9000

  datanode:
    image: dslab/hadoop-datanode
    networks:
      - hdrs
    volumes:
      - datanode:/hadoop/dfs/data
    env_file:
      - ./hadoop.env
    environment:
      SERVICE_PRECONDITION: "namenode:50070"
    deploy:
      mode: global
      restart_policy:
        condition: on-failure

  resourcemanager:
    image: dslab/hadoop-resourcemanager
    networks:
      - hdrs
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075"
    env_file:
      - ./hadoop.env
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure
    healthcheck:
      disable: true
    ports:
      - 8088:8088

  nodemanager:
    image: dslab/hadoop-nodemanager
    networks:
      - hdrs
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
    ports:
      - 8042:8042

  historyserver:
    image: dslab/hadoop-historyserver
    networks:
      - hdrs
    volumes:
      - hadoop_historyserver:/hadoop/yarn/timeline
    environment:
      SERVICE_PRECONDITION: "namenode:50070 datanode:50075 resourcemanager:8088"
    env_file:
      - ./hadoop.env
    deploy:
      mode: replicated
      replicas: 1

volumes:
  datanode:
  namenode:
  hadoop_historyserver:

networks:
  hdrs:
    external:
      name: hdrs
